# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-23 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studykurs', '0005_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='favorite_course',
            new_name='favorite_courses',
        ),
    ]
